### ISSUE TITLE
 Unable to access GUI of the virtual machines of KVM

### ISSUE THREAD

**Issue by sneha2310** [odivlad/webvirtmgr-docker#1]
![image](https://user-images.githubusercontent.com/67871362/186167082-575861ee-1a22-4cd1-907a-75dfae67e193.png)
![image](https://user-images.githubusercontent.com/67871362/186167191-e062da0a-82cc-4bc9-a5b6-8dfe53947c12.png)
![image](https://user-images.githubusercontent.com/67871362/186167389-3cc41422-5445-4e7b-912a-de8ccce0e13a.png)
I am unable to access GUI of the virtual machines of KVM.
Please guide me!!!!
Thank you in advance.

**Comment by odivlad** [comment]
Can you try to switch from https to http?

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186334142-01dcedbd-f6ee-4955-a0ef-c94ce210c01b.png)
It  is still giving error.
Please help me!!

**Comment by odivlad** [comment]
Looks like qemu is not listening for the VNC socket or it is unreachable for some reason (access to it is closed by firewall with `REJECT` action, or it is listening on the 127.0.0.1).
Please check libvirt/qemu VNC settings. Webvirtmgr requires network access to qemu vnc socket.

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186357203-6a869b87-5271-4e8c-95e2-6c18ef0c1b41.png)
But it is open on the server on which I try to get the instance console.

**Comment by odivlad** [comment]
Check the running qemu process whether it is listening for `0.0.0.0:59XX`.
If it does, check tcp connection from webvirtmgr-console container to qemu's VNC socket with telnet/etc.

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186371979-90c576eb-e6a2-4de7-81b7-52f5dc6b84d2.png)
Yes, it is running.

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186374105-b615098b-70e1-4bf7-84e6-796dae0dbd21.png)
![image](https://user-images.githubusercontent.com/67871362/186374365-619a7fda-bc35-43f3-8267-bc888a3a135f.png)
It is showing something like this.

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186377136-7bd0782c-2a38-4620-bec0-d1a7dfcfd6b3.png)
Is installed app don't require console???

**Comment by sneha2310** [comment]
![image](https://user-images.githubusercontent.com/67871362/186379275-159826c0-90eb-487a-a3de-db3fa3011c2c.png)
The console of webvirtmgr shows this error

**Comment by odivlad** [comment]
> https://github.com/odivlad/webvirtmgr-docker/issues/1#issuecomment-1225406024

I mean you should check whether from webvirt-console container the qemu vnc socket is available.

Regarding the error with interfaces - I can't say about the reason, I'm not a maintainer of a webvirtmgr code.

**Comment by sneha2310** [comment]
Thank you for your guidance and time. Now, I can easily access the GUI of the instances.

**Comment by odivlad** [comment]
What was the reason?
I'll update docs.

**Comment by sneha2310** [comment]
Actually I was just doing ssh stuffs only in webvirt container not in
webvirt-console container, that's why this issue arises.
Sorry for late reply.
Thanks for your support.
